name: mongo_example
description: A sample command-line application.
version: 1.0.0
publish_to: none # Not for publishing, example only


environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  bcrypt: ^1.1.3
  fletch:
    path: ../../../packages/fletch
  dart_jsonwebtoken: ^2.17.0

  mongo_dart: ^0.10.4
  mongo_pool: ^1.4.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
