name: fletch
description: A fast, Express-inspired HTTP framework for Dart
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  async: ^2.11.0
  crypto: ^3.0.3
  get_it: ^8.0.3
  http: ^1.2.2
  logger: ^2.5.0
  meta: ^1.16.0
  mime: ^2.0.0
  uri: ^1.0.0
  uuid: ^4.5.1
  xml: ^6.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
