name: mongo_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  bcrypt: ^1.1.3
  dart_express:
    path: ../../../packages/dart_express
  dart_jsonwebtoken: ^2.17.0

  mongo_dart: ^0.10.4
  mongo_pool: ^1.4.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
